use dblojinha;

CREATE TABLE PRODUTOS (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
	NOME VARCHAR(100),
	PREÇO DECIMAL (10,2),
	ESTOQUE INT,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED
(
	[CODIGO]
	) ON [PRIMARY]
) ON [PRIMARY]
GO