use dblojinha;

CREATE TABLE CLIENTES (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(20),
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED
(
	[CODIGO]
	) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE)
VALUES('Marcio Moura', 'marcio.bio@senac.com', '69999303424')

SELECT * FROM CLIENTES;